# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build boogle maps with Maven
      run: mvn -B package --file ./P02-VehiclesAPI/boogle-maps/pom.xml
    - name: Build eureka server with Maven
      run: mvn -B package --file ./P02-VehiclesAPI/eureka-server/pom.xml
    - name: Build pricing service with Maven
      run: mvn -B package --file ./P02-VehiclesAPI/pricing-service/pom.xml
    - name: Build vehicles api with Maven
      run: mvn -B package --file ./P02-VehiclesAPI/vehicles-api/pom.xml
